### PR TITLE
Reorder in folder structure

### PR DESCRIPTION
**Pull request by sacdallago**

### CODE REVIEW

**Comment by juanmirocks** [comment]
:) 

I agree this tidies things up. On the other hand, this creates to me a few problems since I have my PATH variable pointing to the main directory. Otherwise I have to put in more sub-directories.

So you have a strong opinion on this? @sacdallago

**Comment by sacdallago** [comment]
It depends on how big this grows :) in traditional software engineering you would say "it's never too early to do things right" but in lean "it's always to early if it's not necessary yet".
I believe that we are too much into biology to be careful about best practices later, thus to me it makes sense to always start the best practices first :)

To solve the path problem, you can write a script in the root? Also: is this repo language agnostic? I write most of my scripts in JavaScript :P

**Comment by juanmirocks** [comment]
Let's do the following: as soon as the repo **hits 10 scripts**, we separate into directories. Otherwise, now, this seems to be like over-engineering. Agree? 😀 I always knew you are a little pain in the ass 😛

You raise a good point. Another possibility would be to split scripts by language (which was the first version of this repo some years ago). So that's another reason before we start splitting into directories.

As for me, any language is allowed. JavaScript is very much welcomed too.

Any scripts to share? 📝

**Comment by juanmirocks** [comment]
btw: before I forget....... @sacdallago well I will try not to forget, if it's the 11th

**Comment by sacdallago** [comment]
ahah oh thanks @juanmirocks :)

Ok! Let's fo it when we hit the 10 scripts! I might have some to share, but they first need to get polished and documented :)

I think it's better to nest them by subject and then, in case, by language :) Once they are nested, in the root we can have a collection of bash scripts to run the scripts out of the box / download python, node, ... / add the folders to the PATH, etc. :)

**Comment by juanmirocks** [comment]
Great ideas. Very much agree. Looking forward to your scripts 😀 @sacdallago

**Comment by juanmirocks** [comment]
Por email y por aquí felicidades campeón   Disfruta de la vida hoy y siempre ❤️ @sacdallago

**Pull request closed without merging**
